### ISSUE TITLE
请问下，数据层可以使用自己喜欢的ORM吗？

### ISSUE THREAD

**Issue by tanshanli** [cyq1162/Taurus.MVC#1]
因为对EF比较熟悉，所以在数据处理这块，框架能否轻松更换为第三方的ORM呢？

**Comment by cyq1162** [comment]
可以。
但有两个方法你需要知道：
MDataRow.CreateForm(实体).SetToAll(View);//绑定行
MDataTable.CreateForm(List<实体>).Bind(View);//绑定表
