### ISSUE TITLE
页面js使用 \" 时，会发生错误：“\”为意外标记。预期标记为“"”或“'”。

### ISSUE THREAD

**Issue by lee9999** [cyq1162/Taurus.MVC#3]
在页面上使用 \" 时， 如：list += "<i class=\"" + $(this).icon + "\" />"；
则在解析页面时会发生错误：“\”为意外标记。预期标记为“"”或“'”。

**Comment by cyq1162** [comment]
如果是：js在后期处理，不会有问题。
如果是后台生成，就要注意一开始是否符合xhtml规则。

有情况可以进QQ群号:6033006

**Comment by cyq1162** [comment]
如果页面的标签不符合xhtml规则，可以用<![CDATA[   不规范的内容  ]]>   包含起来。
