### ISSUE TITLE
请问：如何在已有的asp.net mvc项目中，使用taurus.mvc来写webapi

### ISSUE THREAD

**Issue by quejuwen** [cyq1162/Taurus.MVC#4]
主要是web.config中httpModules中被 taurus.mvc接管了，原有的mvc就不起作用，如何实现共存？

**Comment by cyq1162** [comment]
本来就是共享的，看源码运行的Demo，不就是共享的：taurus.cyqdata.com

**Comment by cyq1162** [comment]
中间有几个版本不是共存，目前已修正，可共存，新版本为：V3.3.1
