### ISSUE TITLE
在.net core 环境下获取GetJson()会报错

### ISSUE THREAD

**Issue by spiritvip** [cyq1162/Taurus.MVC#5]
((Microsoft.AspNetCore.Server.IIS.Core.WrappingStream)this.context.Request.Body).Length = '((Microsoft.AspNetCore.Server.IIS.Core.WrappingStream)this.context.Request.Body).Length' threw an exception of type 'System.NotSupportedException'

**Comment by cyq1162** [comment]
已做兼容性处理，更新源码即可（2019-05-20)
