### ISSUE TITLE
并发请求只会返回一个请求

### ISSUE THREAD

**Issue by spiritvip** [cyq1162/Taurus.MVC#7]
Taurus.mvc .net core  版本 第一次启动 并发请求只会返回一个请求，所有结果在这个请求一起返回，其它的显示  404 ，第二次请求正常返回.  
错误日志记录  ：
The response headers cannot be modified because the response has already started.

**Comment by cyq1162** [comment]
已修正netcore下并发的问题（更新cyq.data版本的源码即可（2018-07-03)
